<?php

namespace App\Models;

use CodeIgniter\Model;

class RoomFacilitiesOptionModel extends Model
{
    protected $table = 'room_facilities';
    protected $primaryKey = 'slug';
    protected $useAutoIncrement = false;
    protected $returnType = 'object';
    protected $useSoftDeletes = false;
    protected $allowedFields = [
        'slug',
        'name',
        'name_id',
        'icon',
        'order_number',
    ];

    // Dates
    protected $useTimestamps = false;

    public function findAll(int $limit = 0, int $offset = 0)
    {
        $this->orderBy("order_number", "asc");
        return parent::findAll($limit, $offset); // TODO: Change the autogenerated stub
    }
}
